const fs = require("fs");
const path = require("path");

const distPath = path.join(__dirname, "..", "dist-editor", "index.html");
const outPath = path.join(__dirname, "..", "app", "editorHtml.ts");

const html = fs.readFileSync(distPath, "utf8");
const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
const content = `// Generated by scripts/inline-editor.js - do not edit
export const editorHtml = \`${escaped}\`;
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, "utf8");
console.log("Wrote app/editorHtml.ts");
